SELECT * FROM SYS.filegroups

ALTER DATABASE STORE 
MODIFY FILEGROUP TEST_TABLE_FG DEFAULT

ALTER DATABASE STORE
MODIFY FILE(NAME='DATAFILE1',
MAXSIZE=UNLIMITED
)

CREATE TABLE TEST
(COL1 CHAR(8000))

DECLARE @i INT =1
WHILE (@i<40000)
BEGIN
	INSERT INTO TEST VALUES(REPLICATE('A',8000))
	SET @i +=1
END

SELECT COUNT(*) FROM TEST

ALTER DATABASE STORE 
REMOVE FILE DATAFILE2