USE MASTER 
GO
IF Not Exists (Select name from sys.databases where name='VLTestDB')
BEGIN
	CREATE DATABASE VLTestDB
	ON PRIMARY
	(NAME=N'VLTestDB' , FILENAME=N'P:\Apress\VLTestDB.MDF'
	,SIZE=4072 KB, FILEGROWTH=0),
	FILEGROUP FG2
	(NAME=N'VLTestDB2' , FILENAME=N'P:\Apress\VLTestDB2.NDF'
	,SIZE=3048 KB, FILEGROWTH=1024),
	(NAME=N'VLTestDB3' , FILENAME=N'P:\Apress\VLTestDB3.NDF'
	,SIZE=3048 KB, FILEGROWTH=1024)
	LOG ON 
	(NAME=N'VLTestDBLog' , FILENAME=N'P:\Apress\VLTestDB_LOG.LDF'
	,SIZE=3048 KB, FILEGROWTH=1024)
END

ALTER DATABASE VLTestDB 
MODIFY FILEGROUP FG2 DEFAULT
------------------------
USE MASTER
GO 
BACKUP DATABASE VLTestDB 
FILEGROUP='FG2'
TO DISK ='P:\Apress\VLTestDB_FG2.BAK'
WITH NAME=N'VLTestDB-Full FILEGROUP BACK',
SKIP,STATS=20;
GO
BACKUP LOG VLTestDB 
TO DISK = 'P:\Apress\VLTestDB_FG_EXAMPLE.TRN'
GO
------------------------
USE MASTER
GO 
RESTORE DATABASE VLTestDB 
FILEGROUP = 'FG2'
FROM DISK='P:\Apress\VLTestDB_FG2.BAK'
WITH FILE=1 , NORECOVERY, REPLACE;
GO
RESTORE LOG VLTestDB 
FILEGROUP = 'FG2'
FROM DISK='P:\Apress\VLTestDB_FG_EXAMPLE.TRN'
WITH FILE=1 , RECOVERY
GO